### ISSUE TITLE
EAEEEEEEEEEEEEE 

### ISSUE THREAD

**Issue by youssef-md** [projeto-de-algoritmos/Grafos2_DijkstraVisualizado#1]
Boa tarde cara, tá aqui no domingão de ultima hora né :smile_cat: 
Estamos junto nessa, boa sorte na sua empreitada :hand:

**Comment by WelisonR** [comment]
Saaaaaalveee!

A vida é feita pra viver perigosamente, então partiu fazer atividade de PAA no domingão de última hora! @youssef-md xD
